# Use the official PostgreSQL image as a base
FROM postgres:16

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=zplatform
ENV POSTGRES_USER=test
ENV POSTGRES_PASSWORD=test@123

# Expose the default PostgreSQL port
EXPOSE 5432
